# when using environment variables, use this pattern:
# `${${SPRING_PROFILES_ACTIVE}_TECHBD_xyz_abc_def:}`
# - sandbox_TECHBD_xyz_abc_def
# - devl_TECHBD_xyz_abc_def
# - stage_TECHBD_xyz_abc_def
# - prod_TECHBD_xyz_abc_def

logging:
  level:
    com:
      opencsv: ERROR
    org:
      springframework: INFO
      hibernate: ERROR
      web: DEBUG
      apache:
        commons:
          vfs2: ERROR   # Apache VFS internals
          fileupload: ERROR             # File upload / temp file handling
        catalina: ERROR                 # Tomcat core
        coyote: ERROR                   # Tomcat req/res
        tomcat: ERROR                   # Tomcat internals      
    techbd:
      service:
        http:
          hub:
            prime:
              api: INFO
    java:
      util:
        concurrent: ERROR               # General concurrency logging
        CompletableFuture: ERROR        # CompletableFuture callbacks/errors
        ForkJoinPool: ERROR             # Thread pool scheduling
    ca:
      uhn: WARN
    root: INFO
    io:
      opentelemetry: TRACE
      micrometer: TRACE
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: techbd-hub-prime
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_ID:}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_SECRET:}
            scope:
              - read:user
          fusionauth:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_FUSIONAUTH_CLIENT_ID:}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_FUSIONAUTH_CLIENT_SECRET:}
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
            provider: fusionauth
            redirect-uri: "{baseUrl}/login/oauth2/code/fusionauth"
        provider:
          fusionauth:
            authorization-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_FUSIONAUTH_AUTHORIZATION_URI:}
            token-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_FUSIONAUTH_TOKEN_URI:}
            user-info-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_FUSIONAUTH_USER_INFO_URI:}
            jwk-set-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_FUSIONAUTH_JWK_SET_URI:}
            user-name-attribute: email    
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 81bdb4df5dbf13
    password: 8d8fbb25e43ffc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2MB
      resolve-lazily: true
springdoc:
  api-docs:
    path: /docs/api/openapi
  swagger-ui.path: /docs/api/interactive/index.html
  swagger-ui:
    doc-expansion: none
  show-actuator: true 

server:
  servlet:
    context-path: /
    session:
      cookie:
        secure: true
        http-only: true
        same-site: LAX
      timeout: 60m

org:
  techbd:
    service:
      http:
        hub:
          prime:
            version: @project.version@
            fhirVersion: r4
        interactions:
          defaultPersistStrategy: "{ \"nature\": \"fs\" }"
          persist:
            db:
              uri-matcher:
                # TODO: figure out why this is not being read in InteractionsFilter
                regex:
                  - .*
                  - [^/Bundle/.*, POST, persistReqPayload persistRespPayload]         
          saveUserDataToInteractions: true
    udi:
      prime:
        jdbc: 
          # the reason `url` and `jdbcUrl` are both supplied is that some poolers
          # like `url` while others (e.g. Hikari, the default) like `jdbcUrl`
          url: ${${SPRING_PROFILES_ACTIVE}_TECHBD_UDI_DS_PRIME_JDBC_URL:}
          jdbcUrl: ${${SPRING_PROFILES_ACTIVE}_TECHBD_UDI_DS_PRIME_JDBC_URL:}
          username: ${${SPRING_PROFILES_ACTIVE}_TECHBD_UDI_DS_PRIME_JDBC_USERNAME:}
          password: ${${SPRING_PROFILES_ACTIVE}_TECHBD_UDI_DS_PRIME_JDBC_PASSWORD:}
          driverClassName: org.postgresql.Driver
          maximumPoolSize: 500 # Set to 500 as per your request
          minimumIdle: 100  # Minimum idle connections in the pool
          idleTimeout: 300000 # 30 seconds to wait for a connection from the pool
          connectionTimeout: 30000  # 5 minutes - idle connections are removed after this time
          maxLifetime: 1800000  # 30 minutes - connections are refreshed after this time
management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics: 
      export: 
        url: ${TECHBD_OPEN_OBSERVE_URL}/api/${TECHBD_OPEN_OBSERVE_STREAM_NAME}/v1/metrics
        enabled: true 
        step: 1m # Interval for pushing metrics 
        headers: 
          enabled: true 
          Authorization: Basic ${TECHBD_OPEN_OBSERVE_PASSWORD}
          organization: default
          service: 
            name: default
    tracing: 
      export:
        enabled: true
      endpoint: ${TECHBD_OPEN_OBSERVE_URL}/api/${TECHBD_OPEN_OBSERVE_STREAM_NAME}/v1/traces
      headers: 
        enabled: true  
        Authorization: Basic ${TECHBD_OPEN_OBSERVE_PASSWORD}
        organization: default
        stream-name: ${TECHBD_OPEN_OBSERVE_STREAM_NAME}-traces
        service: 
          name: default